language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/spf13/cobra
  - go get github.com/spf13/viper
script:
  - $HOME/gopath/bin/goveralls -repotoken 4dAp4ODDdhtCTRp65JsfLr15ewtqqRkLZ
